package command

func pluginCommandHelp(command string) (commandHelp, bool) {
	switch command {
	case "plugin":
		return commandHelp{Name: "plugin", Short: "List, search, install and run gofly generation plugins.", Usage: "gofly plugin list | gofly plugin search --registry <url-or-path> [query] | gofly plugin install --remote <repo>@<version> | gofly plugin run <plugin> [flags]", Commands: []helpCommand{{Name: "list", Short: "list built-in and cached plugins"}, {Name: "search", Short: "search a plugin registry index"}, {Name: "install", Short: "download a version-pinned remote plugin"}, {Name: "uninstall", Short: "remove a version-pinned cached plugin"}, {Name: "run", Short: "run a built-in, cached or external plugin"}}, Examples: []string{"gofly plugin list --json", "gofly plugin search --registry ./plugins.json redis --json", "gofly plugin install --remote https://example.com/gofly-plugin@v1.2.3 --json", "gofly plugin run --remote https://example.com/gofly-plugin@v1.2.3 --name hello --module example.com/hello --dir . --json", "gofly plugin run --go-plugin ./plugins --name hello --module example.com/hello --dir ."}}, true
	case "plugin list":
		return commandHelp{Name: "plugin list", Short: "List built-in generation plugins and cached generation plugins.", Usage: "gofly plugin list [--format text|json] [--json]", Flags: []string{"--format <format>  output format: text|json", "--json             output JSON"}, Examples: []string{"gofly plugin list", "gofly plugin list --json"}}, true
	case "plugin search":
		return commandHelp{Name: "plugin search", Short: "Search a plugin registry index without installing plugins.", Usage: "gofly plugin search --registry <url-or-path> [query] [--format text|json] [--json]", Flags: []string{"--registry <url-or-path>  registry JSON URL or path", "--query <query>           search query, also accepted as positional", "--format <format>         output format: text|json", "--json                    output JSON"}, Examples: []string{"gofly plugin search --registry ./plugins.json", "gofly plugin search --registry https://example.com/gofly-plugins.json redis --json"}}, true
	case "plugin install":
		return commandHelp{Name: "plugin install", Short: "Install a version-pinned remote generation plugin into ~/.cache/gofly/plugins/<hash>.", Usage: "gofly plugin install --remote <repo-or-url>@<version> [--json]", Flags: []string{"--remote <repo>@<version>  version-pinned plugin URL, file:// path, file path or executable directory", "--json                    output JSON with binary digest metadata"}, Examples: []string{"gofly plugin install --remote https://example.com/gofly-plugin@v1.2.3", "gofly plugin install --remote ./plugins/my-plugin@dev --json"}}, true
	case "plugin uninstall":
		return commandHelp{Name: "plugin uninstall", Short: "Remove a version-pinned remote generation plugin from ~/.cache/gofly/plugins/<hash>.", Usage: "gofly plugin uninstall --remote <repo-or-url>@<version> [--json]", Flags: []string{"--remote <repo>@<version>  version-pinned plugin identity", "--json                    output JSON"}, Examples: []string{"gofly plugin uninstall --remote https://example.com/gofly-plugin@v1.2.3 --json"}}, true
	case "plugin run":
		return commandHelp{Name: "plugin run", Short: "Run a built-in or external generation plugin, including cached plugins.", Usage: "gofly plugin run <plugin-name-or-path> --name <service> --module <module> --dir <dir> [--command <kind>] [--json]", Flags: []string{"--name <name>                  service name", "--module <path>                Go module path", "--dir <dir>                    service directory", "--command <kind>               plugin command: service|handler|model", "--remote <repo>@<version>      auto-install and run cached remote plugin", "--go-plugin <path-or-dir>      run one executable plugin or traverse a directory of executable plugins", "--json                         output JSON run summary"}, Examples: []string{"gofly plugin run ./my-plugin --name hello --module example.com/hello --dir . --json", "gofly plugin run --remote https://example.com/gofly-plugin@v1.2.3 --name hello --module example.com/hello --dir .", "gofly plugin run --go-plugin ./plugins --command service --dir ."}}, true
	default:
		return commandHelp{}, false
	}
}
