apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gofly-app
  labels:
    app.kubernetes.io/name: gofly-app
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: gofly-app
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8081
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
