package generator

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"time"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

type GRPCScaffoldOptions struct {
	ProtoFile       string
	ProtoFiles      []string
	ProtoPath       []string
	Dir             string
	Module          string
	Name            string
	NameFromPackage bool
	NoClient        bool
	Multiple        bool
	RequireMultiple bool
	Protoc          string
	Timeout         time.Duration
}

type grpcApplicationContract struct {
	RequestImport  string
	RequestType    string
	ResponseImport string
	ResponseType   string
	HasRequest     bool
}

const grpcGeneratedApplicationMarker = "// Code generated by gofly RPC scaffold; application stub is preserved after creation."

func GenerateGRPCScaffold(ctx context.Context, opts GRPCScaffoldOptions) error {
	protoFiles := grpcScaffoldProtoFiles(opts)
	if len(protoFiles) == 0 {
		return errors.New("proto file is required")
	}
	opts.ProtoFile = protoFiles[0]
	if opts.Timeout <= 0 {
		opts.Timeout = 30 * time.Second
	}
	if opts.Dir == "" {
		opts.Dir = "."
	}
	moduleTarget, err := safeRelativeTarget(opts.Dir, "go.mod", "grpc scaffold")
	if err != nil {
		return err
	}
	if err := rejectExistingSymlinkTarget(moduleTarget, "grpc scaffold module"); err != nil {
		return err
	}
	if _, err := os.Stat(moduleTarget); err == nil {
		existing, err := inferModule(opts.Dir)
		if err != nil {
			return err
		}
		if opts.Module != "" && opts.Module != existing {
			return errors.New("scaffold module differs from existing go.mod")
		}
		opts.Module = existing
	} else if !errors.Is(err, os.ErrNotExist) {
		return err
	}
	if opts.Module == "" {
		module, err := inferModule(opts.Dir)
		if err != nil {
			module, err = inferGRPCScaffoldModule(opts)
			if err != nil {
				return err
			}
		}
		opts.Module = module
	}
	if !isSafeProjectFeatureModulePath(opts.Module) {
		return fmt.Errorf("invalid scaffold module %q", opts.Module)
	}
	if err := validateNativeGRPCToolchain(); err != nil {
		return err
	}
	stage, err := os.MkdirTemp("", "gofly-grpc-scaffold-*")
	if err != nil {
		return err
	}
	defer os.RemoveAll(stage)
	protoNames, includes, err := resolveGRPCScaffoldInputs(protoFiles, opts.ProtoPath)
	if err != nil {
		return err
	}
	descriptorPath := filepath.Join(stage, "descriptor.pb")
	if err := GenerateStandardProto(ctx, ProtocOptions{
		ProtoFiles: protoNames, ProtoPath: includes, GoOut: stage, GoGRPCOut: stage, Protoc: opts.Protoc, Timeout: opts.Timeout,
		ExtraArgs: []string{"--go_opt=module=" + opts.Module, "--go-grpc_opt=module=" + opts.Module, "--descriptor_set_out=" + descriptorPath, "--include_imports"},
	}); err != nil {
		return err
	}
	data, err := ReadFileUnderRoot(stage, "descriptor.pb", "grpc descriptors")
	if err != nil {
		return err
	}
	var descriptors descriptorpb.FileDescriptorSet
	if err := proto.Unmarshal(data, &descriptors); err != nil {
		return fmt.Errorf("decode proto descriptors: %w", err)
	}
	plugin, err := (protogen.Options{}).New(&pluginpb.CodeGeneratorRequest{ProtoFile: descriptors.File, FileToGenerate: protoNames})
	if err != nil {
		return fmt.Errorf("resolve proto Go types: %w", err)
	}
	primaryFiles := make([]*protogen.File, 0, len(protoNames))
	serviceCount := 0
	for _, name := range protoNames {
		file := plugin.FilesByPath[name]
		if file == nil {
			return fmt.Errorf("generated proto descriptor %q is missing", name)
		}
		if !strings.HasPrefix(string(file.GoImportPath), opts.Module+"/") {
			return fmt.Errorf("proto %q go_package must be a package under the scaffold module", name)
		}
		primaryFiles = append(primaryFiles, file)
		serviceCount += len(file.Services)
	}
	if serviceCount == 0 {
		return errors.New("proto service is required")
	}
	if opts.RequireMultiple && serviceCount > 1 && !opts.Multiple {
		return errors.New("proto inputs define multiple services; rerun with --multiple")
	}
	if opts.Name == "" {
		opts.Name = strings.TrimSuffix(filepath.Base(opts.ProtoFile), filepath.Ext(opts.ProtoFile))
		if opts.NameFromPackage && strings.TrimSpace(string(primaryFiles[0].Desc.Package())) != "" {
			opts.Name = lowerName(string(primaryFiles[0].Desc.Package()))
		}
	}
	if !token.IsIdentifier(opts.Name) {
		return fmt.Errorf("invalid scaffold name %q", opts.Name)
	}
	if err := migrateLegacyGRPCAdapterDirectory(opts.Dir, opts.Module); err != nil {
		return err
	}
	serverTarget := "internal/api/grpc/v1/register.gen.go"
	serverTargetPath, err := safeRelativeTarget(opts.Dir, serverTarget, "grpc scaffold")
	if err != nil {
		return err
	}
	entries, err := os.ReadDir(filepath.Dir(serverTargetPath))
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	for _, entry := range entries {
		if strings.HasSuffix(entry.Name(), "_grpc.gen.go") && entry.Name() != filepath.Base(serverTargetPath) {
			return errors.New("another grpc scaffold already owns this output root")
		}
	}
	primaryPaths := make(map[string]struct{}, len(primaryFiles))
	for _, file := range primaryFiles {
		primaryPaths[file.Desc.Path()] = struct{}{}
	}
	for _, dependency := range plugin.Files {
		if _, primary := primaryPaths[dependency.Desc.Path()]; primary || !strings.HasPrefix(string(dependency.GoImportPath), opts.Module+"/") {
			continue
		}
		if err := GenerateStandardProto(ctx, ProtocOptions{ProtoFile: dependency.Desc.Path(), ProtoPath: includes, GoOut: stage, GoGRPCOut: stage, Protoc: opts.Protoc, Timeout: opts.Timeout, ExtraArgs: []string{"--go_opt=module=" + opts.Module, "--go-grpc_opt=module=" + opts.Module}}); err != nil {
			return err
		}
	}
	files := make(map[string][]byte)
	if err := filepath.WalkDir(stage, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() || path == descriptorPath {
			return nil
		}
		if !entry.Type().IsRegular() {
			return fmt.Errorf("non-regular protoc output %s", path)
		}
		rel, err := filepath.Rel(stage, path)
		if err != nil {
			return err
		}
		content, err := ReadFileUnderRoot(stage, rel, "protoc output")
		if err != nil {
			return err
		}
		files[rel] = content
		return nil
	}); err != nil {
		return err
	}
	owned := make(map[string]bool)
	if err := renderGRPCScaffold(plugin, primaryFiles, opts, files, owned); err != nil {
		return err
	}
	if err := mergeGRPCScaffoldSharedFiles(opts.Dir, files, owned); err != nil {
		return err
	}
	paths := make([]string, 0, len(files))
	for name, content := range files {
		target, err := safeRelativeTarget(opts.Dir, name, "grpc scaffold")
		if err != nil {
			return err
		}
		if info, err := os.Lstat(target); err == nil {
			if !info.Mode().IsRegular() {
				return fmt.Errorf("grpc scaffold target %q must be a regular file", name)
			}
			if !owned[name] {
				existing, err := ReadFileUnderRoot(opts.Dir, name, "grpc scaffold")
				if err != nil {
					return err
				}
				header, _, _ := strings.Cut(string(content), "\n")
				if !strings.HasPrefix(string(existing), header+"\n") {
					return fmt.Errorf("refusing to overwrite non-generated file %q", name)
				}
				for line := range strings.SplitSeq(string(existing), "\n") {
					if strings.HasPrefix(line, "// source: ") && !strings.Contains(string(content), "\n"+line+"\n") {
						return fmt.Errorf("grpc scaffold output %q belongs to another proto", name)
					}
				}
			}
		} else if !errors.Is(err, os.ErrNotExist) {
			return err
		}
		if filepath.Ext(name) == ".go" {
			formatted, err := format.Source(content)
			if err != nil {
				return fmt.Errorf("format %s: %w", name, err)
			}
			files[name] = formatted
		}
		paths = append(paths, name)
	}
	sort.Strings(paths)
	for _, name := range paths {
		if owned[name] {
			var err error
			if filepath.Clean(name) == filepath.Join("etc", opts.Name+".json") {
				err = mergeGRPCScaffoldJSONDefaults(opts.Dir, name, files[name])
			} else {
				err = writeGeneratedExtensionFile(opts.Dir, name, files[name])
			}
			if err != nil {
				return err
			}
		} else if err := writeGeneratedFileUnder(opts.Dir, name, files[name]); err != nil {
			return err
		}
	}
	return nil
}

func migrateLegacyGRPCAdapterDirectory(root, module string) error {
	rootInfo, err := os.Lstat(root)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("inspect project root before grpc adapter migration: %w", err)
	}
	if !rootInfo.IsDir() || rootInfo.Mode()&os.ModeSymlink != 0 {
		return errors.New("grpc adapter migration root must be a regular directory")
	}
	legacy, err := SafeTarget(root, filepath.Join("internal", "api", "rpc"), "legacy grpc adapter directory")
	if err != nil {
		return err
	}
	target, err := SafeTarget(root, filepath.Join("internal", "api", "grpc"), "grpc adapter directory")
	if err != nil {
		return err
	}
	legacyInfo, err := os.Lstat(legacy)
	if errors.Is(err, os.ErrNotExist) {
		return rewriteLegacyGRPCImports(root, module)
	}
	if err != nil {
		return fmt.Errorf("inspect legacy grpc adapter directory: %w", err)
	}
	if !legacyInfo.IsDir() || legacyInfo.Mode()&os.ModeSymlink != 0 {
		return errors.New("legacy grpc adapter path internal/api/rpc must be a regular directory")
	}
	if _, err := os.Lstat(target); err == nil {
		return errors.New("both internal/api/rpc and internal/api/grpc exist; reconcile them before regenerating")
	} else if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("inspect grpc adapter directory: %w", err)
	}
	if err := rejectExistingSymlinkTarget(filepath.Dir(target), "grpc adapter directory parent"); err != nil {
		return err
	}
	if err := os.Rename(legacy, target); err != nil {
		return fmt.Errorf("migrate internal/api/rpc to internal/api/grpc: %w", err)
	}
	return rewriteLegacyGRPCImports(root, module)
}

func rewriteLegacyGRPCImports(root, module string) error {
	oldPrefix := strings.TrimSpace(module) + "/internal/api/rpc"
	newPrefix := strings.TrimSpace(module) + "/internal/api/grpc"
	if oldPrefix == "/internal/api/rpc" {
		return errors.New("module is required to migrate grpc adapter imports")
	}
	return filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() || !entry.Type().IsRegular() || filepath.Ext(entry.Name()) != ".go" {
			return nil
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		data, err := ReadFileUnderRoot(root, rel, "legacy grpc import migration")
		if err != nil {
			return err
		}
		parsed, err := parser.ParseFile(token.NewFileSet(), rel, data, parser.ImportsOnly)
		if err != nil {
			return fmt.Errorf("parse grpc import migration file %s: %w", rel, err)
		}
		type importEdit struct {
			start, end int
			value      string
		}
		edits := make([]importEdit, 0)
		for _, spec := range parsed.Imports {
			pathValue, err := strconv.Unquote(spec.Path.Value)
			if err != nil {
				return fmt.Errorf("decode grpc import in %s: %w", rel, err)
			}
			if pathValue != oldPrefix && !strings.HasPrefix(pathValue, oldPrefix+"/") {
				continue
			}
			edits = append(edits, importEdit{
				start: int(spec.Path.Pos() - 1),
				end:   int(spec.Path.End() - 1),
				value: strconv.Quote(newPrefix + strings.TrimPrefix(pathValue, oldPrefix)),
			})
		}
		if len(edits) == 0 {
			return nil
		}
		for index := len(edits) - 1; index >= 0; index-- {
			edit := edits[index]
			data = append(append(append([]byte(nil), data[:edit.start]...), edit.value...), data[edit.end:]...)
		}
		info, err := os.Stat(path)
		if err != nil {
			return err
		}
		return WriteFileUnderRoot(root, rel, data, info.Mode().Perm(), generatedDirMode, "legacy grpc import migration")
	})
}

func mergeGRPCScaffoldSharedFiles(root string, files map[string][]byte, owned map[string]bool) error {
	splitRPCConfig, err := ReadFileUnderRoot(root, "internal/config/rpc.go", "grpc split config")
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	hasSplitRPCConfig := err == nil &&
		bytes.Contains(splitRPCConfig, []byte("type RPCClientConfig struct")) &&
		bytes.Contains(splitRPCConfig, []byte("func ValidateRPC"))

	for _, item := range []struct {
		path             string
		requiredMarker   string
		rpcMarker        string
		mergeStruct      string
		mergeConstructor string
		renameFunction   map[string]string
	}{
		{path: "internal/config/config.go", requiredMarker: "type OpenAPIConfig struct", rpcMarker: "type RPCClientConfig struct", mergeStruct: "Config", renameFunction: map[string]string{"Validate": "ValidateRPC"}},
		{path: "internal/svc/service_context.go", requiredMarker: "type RPCMuxDiagnosisClient interface", rpcMarker: "type rpcClientResource struct", mergeStruct: "ServiceContext", mergeConstructor: "NewServiceContext"},
	} {
		existing, err := ReadFileUnderRoot(root, item.path, "grpc shared scaffold")
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			return err
		}
		if item.path == "internal/svc/service_context.go" &&
			bytes.Contains(existing, []byte("clientConns")) &&
			bytes.Contains(existing, []byte("InitRPCClients")) {
			files[item.path] = existing
			owned[item.path] = false
			continue
		}
		if item.path == "internal/config/config.go" && hasSplitRPCConfig {
			merged, err := mergeGoScaffoldSplitConfig(existing, files[item.path], splitRPCConfig, item.mergeStruct)
			if err != nil {
				return fmt.Errorf("merge RPC scaffold %s with split RPC config: %w", item.path, err)
			}
			files[item.path] = merged
			owned[item.path] = false
			continue
		}
		if bytes.Contains(existing, []byte(item.rpcMarker)) {
			files[item.path] = existing
			owned[item.path] = false
			continue
		}
		if !bytes.Contains(existing, []byte(item.requiredMarker)) {
			return fmt.Errorf("cannot merge RPC scaffold into user-owned %s", item.path)
		}
		generated := files[item.path]
		if item.path == "internal/svc/service_context.go" {
			generated = bytes.ReplaceAll(generated, []byte("rpcClients"), []byte("grpcClients"))
			generated = bytes.ReplaceAll(generated, []byte("rpcResolvers"), []byte("grpcResolvers"))
		}
		merged, err := mergeGoScaffoldSource(existing, generated, item.mergeStruct, item.mergeConstructor, item.renameFunction)
		if err != nil {
			return fmt.Errorf("merge RPC scaffold %s: %w", item.path, err)
		}
		files[item.path] = merged
		owned[item.path] = false
	}
	return nil
}

func mergeGoScaffoldSource(existing, generated []byte, mergeStruct, mergeConstructor string, renameFunction map[string]string) ([]byte, error) {
	fset := token.NewFileSet()
	base, err := parser.ParseFile(fset, "existing.go", existing, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	addition, err := parser.ParseFile(fset, "generated.go", generated, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	mergeGoImports(base, addition)
	existingNames := goDeclarationNames(base)
	baseStruct := goStructDeclaration(base, mergeStruct)
	additionStruct := goStructDeclaration(addition, mergeStruct)
	if baseStruct == nil || additionStruct == nil {
		return nil, fmt.Errorf("shared struct %s is missing", mergeStruct)
	}
	mergeGoStructFields(baseStruct, additionStruct)
	if mergeConstructor != "" {
		if err := mergeGoConstructor(base, addition, mergeConstructor); err != nil {
			return nil, err
		}
	}
	for _, decl := range addition.Decls {
		if _, ok := decl.(*ast.GenDecl); ok {
			gen := decl.(*ast.GenDecl)
			if gen.Tok == token.IMPORT {
				continue
			}
		}
		name := goDeclarationName(decl)
		if name == mergeStruct || name == mergeConstructor {
			continue
		}
		if replacement := renameFunction[name]; replacement != "" {
			if fn, ok := decl.(*ast.FuncDecl); ok {
				fn.Name.Name = replacement
				name = replacement
			}
		}
		if name != "" {
			if _, exists := existingNames[name]; exists {
				continue
			}
			existingNames[name] = struct{}{}
		}
		base.Decls = append(base.Decls, decl)
	}
	pruneUnusedGoImports(base)
	var output bytes.Buffer
	if err := format.Node(&output, fset, base); err != nil {
		return nil, err
	}
	return output.Bytes(), nil
}

func mergeGoScaffoldSplitConfig(existing, generated, split []byte, mergeStruct string) ([]byte, error) {
	fset := token.NewFileSet()
	base, err := parser.ParseFile(fset, "existing.go", existing, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	addition, err := parser.ParseFile(fset, "generated.go", generated, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	splitFile, err := parser.ParseFile(fset, "split.go", split, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	splitNames := goDeclarationNames(splitFile)
	kept := make([]ast.Decl, 0, len(base.Decls))
	for _, decl := range base.Decls {
		name := goDeclarationName(decl)
		if name != "" && name != mergeStruct {
			if _, duplicate := splitNames[name]; duplicate {
				continue
			}
		}
		kept = append(kept, decl)
	}
	base.Decls = kept
	baseStruct := goStructDeclaration(base, mergeStruct)
	additionStruct := goStructDeclaration(addition, mergeStruct)
	if baseStruct == nil || additionStruct == nil {
		return nil, fmt.Errorf("shared struct %s is missing", mergeStruct)
	}
	addedFields := mergeGoStructFields(baseStruct, additionStruct)
	mergeGoImportsUsedByFields(base, addition, addedFields)
	pruneUnusedGoImports(base)
	var output bytes.Buffer
	if err := format.Node(&output, fset, base); err != nil {
		return nil, err
	}
	return output.Bytes(), nil
}

func pruneUnusedGoImports(file *ast.File) {
	used := make(map[string]struct{})
	ast.Inspect(file, func(node ast.Node) bool {
		selector, ok := node.(*ast.SelectorExpr)
		if !ok {
			return true
		}
		if pkg, ok := selector.X.(*ast.Ident); ok {
			used[pkg.Name] = struct{}{}
		}
		return true
	})
	imports := make([]*ast.ImportSpec, 0, len(file.Imports))
	for _, spec := range file.Imports {
		name := goImportName(spec)
		if name == "_" || name == "." {
			imports = append(imports, spec)
			continue
		}
		if _, ok := used[name]; ok {
			imports = append(imports, spec)
		}
	}
	file.Imports = imports
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.IMPORT {
			continue
		}
		specs := make([]ast.Spec, 0, len(gen.Specs))
		for _, raw := range gen.Specs {
			spec, ok := raw.(*ast.ImportSpec)
			if !ok {
				continue
			}
			name := goImportName(spec)
			if name == "_" || name == "." {
				specs = append(specs, spec)
				continue
			}
			if _, ok := used[name]; ok {
				specs = append(specs, spec)
			}
		}
		gen.Specs = specs
	}
}

func goImportName(spec *ast.ImportSpec) string {
	if spec.Name != nil {
		return spec.Name.Name
	}
	name := strings.Trim(spec.Path.Value, "\"")
	if index := strings.LastIndexByte(name, '/'); index >= 0 {
		return name[index+1:]
	}
	return name
}

func mergeGoImports(base, addition *ast.File) {
	existing := make(map[string]struct{}, len(base.Imports))
	for _, spec := range base.Imports {
		existing[goImportKey(spec)] = struct{}{}
	}
	var target *ast.GenDecl
	for _, decl := range base.Decls {
		if gen, ok := decl.(*ast.GenDecl); ok && gen.Tok == token.IMPORT {
			target = gen
			break
		}
	}
	if target == nil {
		target = &ast.GenDecl{Tok: token.IMPORT, Lparen: 1}
		base.Decls = append([]ast.Decl{target}, base.Decls...)
	}
	for _, spec := range addition.Imports {
		if _, exists := existing[goImportKey(spec)]; exists {
			continue
		}
		clone := &ast.ImportSpec{Path: &ast.BasicLit{Kind: token.STRING, Value: spec.Path.Value}}
		if spec.Name != nil {
			clone.Name = ast.NewIdent(spec.Name.Name)
		}
		target.Specs = append(target.Specs, clone)
		base.Imports = append(base.Imports, clone)
		existing[goImportKey(spec)] = struct{}{}
	}
}

func goImportKey(spec *ast.ImportSpec) string {
	name := ""
	if spec.Name != nil {
		name = spec.Name.Name
	}
	return name + "\x00" + spec.Path.Value
}

func goDeclarationNames(file *ast.File) map[string]struct{} {
	names := make(map[string]struct{})
	for _, decl := range file.Decls {
		if name := goDeclarationName(decl); name != "" {
			names[name] = struct{}{}
		}
	}
	return names
}

func goDeclarationName(decl ast.Decl) string {
	switch value := decl.(type) {
	case *ast.FuncDecl:
		if value.Recv == nil || len(value.Recv.List) == 0 {
			return value.Name.Name
		}
		receiver := value.Recv.List[0].Type
		if pointer, ok := receiver.(*ast.StarExpr); ok {
			receiver = pointer.X
		}
		if receiverName, ok := receiver.(*ast.Ident); ok {
			return receiverName.Name + "." + value.Name.Name
		}
	case *ast.GenDecl:
		if len(value.Specs) == 1 {
			if spec, ok := value.Specs[0].(*ast.TypeSpec); ok {
				return spec.Name.Name
			}
		}
	}
	return ""
}

func goStructDeclaration(file *ast.File, name string) *ast.StructType {
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}
		for _, raw := range gen.Specs {
			spec, ok := raw.(*ast.TypeSpec)
			if !ok || spec.Name.Name != name {
				continue
			}
			structure, _ := spec.Type.(*ast.StructType)
			return structure
		}
	}
	return nil
}

func mergeGoStructFields(base, addition *ast.StructType) []*ast.Field {
	existing := make(map[string]struct{})
	for _, field := range base.Fields.List {
		for _, name := range field.Names {
			existing[name.Name] = struct{}{}
		}
	}
	added := make([]*ast.Field, 0)
	for _, field := range addition.Fields.List {
		if len(field.Names) == 0 {
			continue
		}
		if _, ok := existing[field.Names[0].Name]; ok {
			continue
		}
		base.Fields.List = append(base.Fields.List, field)
		added = append(added, field)
		existing[field.Names[0].Name] = struct{}{}
	}
	return added
}

func mergeGoImportsUsedByFields(base, addition *ast.File, fields []*ast.Field) {
	used := make(map[string]struct{})
	for _, field := range fields {
		ast.Inspect(field.Type, func(node ast.Node) bool {
			selector, ok := node.(*ast.SelectorExpr)
			if !ok {
				return true
			}
			if pkg, ok := selector.X.(*ast.Ident); ok {
				used[pkg.Name] = struct{}{}
			}
			return true
		})
	}
	if len(used) == 0 {
		return
	}
	filtered := &ast.File{}
	for _, spec := range addition.Imports {
		name := goImportName(spec)
		if _, ok := used[name]; ok {
			filtered.Imports = append(filtered.Imports, spec)
		}
	}
	mergeGoImports(base, filtered)
}

func mergeGoConstructor(base, addition *ast.File, name string) error {
	baseFn, additionFn := goFunctionDeclaration(base, name), goFunctionDeclaration(addition, name)
	if baseFn == nil || additionFn == nil {
		return fmt.Errorf("shared constructor %s is missing", name)
	}
	baseLiteral, additionLiteral := goReturnedComposite(baseFn), goReturnedComposite(additionFn)
	if baseLiteral == nil || additionLiteral == nil {
		return fmt.Errorf("shared constructor %s must return a struct literal", name)
	}
	existing := make(map[string]struct{})
	for _, element := range baseLiteral.Elts {
		if pair, ok := element.(*ast.KeyValueExpr); ok {
			if key, ok := pair.Key.(*ast.Ident); ok {
				existing[key.Name] = struct{}{}
			}
		}
	}
	added := false
	for _, element := range additionLiteral.Elts {
		pair, ok := element.(*ast.KeyValueExpr)
		if !ok {
			continue
		}
		key, ok := pair.Key.(*ast.Ident)
		if !ok {
			continue
		}
		if _, ok := existing[key.Name]; ok {
			continue
		}
		baseLiteral.Elts = append(baseLiteral.Elts, element)
		added = true
	}
	if added {
		existingStatements := make(map[string]struct{}, len(baseFn.Body.List))
		for _, statement := range baseFn.Body.List {
			existingStatements[goNodeText(statement)] = struct{}{}
		}
		for _, statement := range additionFn.Body.List {
			if _, ok := statement.(*ast.ReturnStmt); !ok {
				if _, exists := existingStatements[goNodeText(statement)]; exists {
					continue
				}
				baseFn.Body.List = append(baseFn.Body.List[:len(baseFn.Body.List)-1], append([]ast.Stmt{statement}, baseFn.Body.List[len(baseFn.Body.List)-1:]...)...)
				existingStatements[goNodeText(statement)] = struct{}{}
			}
		}
	}
	return nil
}

func goNodeText(node ast.Node) string {
	var output bytes.Buffer
	if err := format.Node(&output, token.NewFileSet(), node); err != nil {
		return ""
	}
	return output.String()
}

func goFunctionDeclaration(file *ast.File, name string) *ast.FuncDecl {
	for _, decl := range file.Decls {
		if fn, ok := decl.(*ast.FuncDecl); ok && fn.Recv == nil && fn.Name.Name == name {
			return fn
		}
	}
	return nil
}

func goReturnedComposite(fn *ast.FuncDecl) *ast.CompositeLit {
	for _, statement := range fn.Body.List {
		returned, ok := statement.(*ast.ReturnStmt)
		if !ok || len(returned.Results) == 0 {
			continue
		}
		expr := returned.Results[0]
		if unary, ok := expr.(*ast.UnaryExpr); ok {
			expr = unary.X
		}
		if literal, ok := expr.(*ast.CompositeLit); ok {
			return literal
		}
	}
	return nil
}

func mergeGRPCScaffoldJSONDefaults(root, name string, defaults []byte) error {
	existing, err := ReadFileUnderRoot(root, name, "grpc scaffold config")
	if errors.Is(err, os.ErrNotExist) {
		return writeGeneratedExtensionFile(root, name, defaults)
	}
	if err != nil {
		return err
	}
	target, err := SafeTarget(root, name, "grpc scaffold config")
	if err != nil {
		return err
	}
	info, err := os.Stat(target)
	if err != nil {
		return fmt.Errorf("stat existing grpc scaffold config %s: %w", name, err)
	}
	var currentValues, defaultValues map[string]any
	if err := json.Unmarshal(existing, &currentValues); err != nil {
		return fmt.Errorf("decode existing grpc scaffold config %s: %w", name, err)
	}
	if err := json.Unmarshal(defaults, &defaultValues); err != nil {
		return fmt.Errorf("decode generated grpc scaffold config %s: %w", name, err)
	}
	if !mergeMissingJSONValues(currentValues, defaultValues) {
		return nil
	}
	merged, err := json.MarshalIndent(currentValues, "", "  ")
	if err != nil {
		return fmt.Errorf("encode merged grpc scaffold config %s: %w", name, err)
	}
	return WriteFileUnderRoot(root, name, append(merged, '\n'), info.Mode().Perm(), generatedDirMode, "grpc scaffold config")
}

func mergeMissingJSONValues(current, defaults map[string]any) bool {
	changed := false
	for key, defaultValue := range defaults {
		currentValue, exists := current[key]
		if !exists {
			current[key] = defaultValue
			changed = true
			continue
		}
		currentObject, currentOK := currentValue.(map[string]any)
		defaultObject, defaultOK := defaultValue.(map[string]any)
		if currentOK && defaultOK && mergeMissingJSONValues(currentObject, defaultObject) {
			changed = true
		}
	}
	return changed
}

func inferGRPCScaffoldModule(opts GRPCScaffoldOptions) (string, error) {
	doc, err := ParseProtoFileWithIncludes(opts.ProtoFile, opts.ProtoPath)
	if err != nil {
		return "", fmt.Errorf("infer scaffold module from proto: %w", err)
	}
	goPackage := strings.TrimSpace(protoGoImportPath(doc.GoPackage))
	for _, marker := range []string{"/internal/", "/pkg/"} {
		if index := strings.Index(goPackage, marker); index > 0 {
			return goPackage[:index], nil
		}
	}
	if base := strings.TrimSpace(filepath.Base(goPackage)); goPackage != "" && base != "." && base != string(filepath.Separator) {
		if module := strings.TrimSuffix(goPackage, "/"+base); module != "" {
			return module, nil
		}
	}
	base := lowerName(filepath.Base(filepath.Clean(opts.Dir)))
	if base != "" && base != "." {
		return base, nil
	}
	return "", errors.New("module is required; pass --module or declare option go_package under the project module")
}

func grpcScaffoldProtoFiles(opts GRPCScaffoldOptions) []string {
	values := make([]string, 0, 1+len(opts.ProtoFiles))
	if strings.TrimSpace(opts.ProtoFile) != "" {
		values = append(values, strings.TrimSpace(opts.ProtoFile))
	}
	for _, value := range opts.ProtoFiles {
		if value = strings.TrimSpace(value); value != "" {
			values = append(values, value)
		}
	}
	return values
}

func resolveGRPCScaffoldInputs(protoFiles, includePaths []string) ([]string, []string, error) {
	absIncludes := make([]string, 0, len(includePaths)+len(protoFiles))
	for _, path := range includePaths {
		if strings.TrimSpace(path) == "" {
			continue
		}
		abs, err := filepath.Abs(path)
		if err != nil {
			return nil, nil, err
		}
		absIncludes = append(absIncludes, filepath.Clean(abs))
	}
	absIncludes = uniqueCleanPaths(absIncludes)
	absFiles := make([]string, 0, len(protoFiles))
	for _, name := range protoFiles {
		abs, err := filepath.Abs(name)
		if err != nil {
			return nil, nil, err
		}
		abs = filepath.Clean(abs)
		absFiles = append(absFiles, abs)
		covered := false
		for _, include := range absIncludes {
			rel, relErr := filepath.Rel(include, abs)
			if relErr == nil && rel != ".." && !strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
				covered = true
				break
			}
		}
		if !covered {
			absIncludes = append(absIncludes, filepath.Dir(abs))
		}
	}
	absIncludes = uniqueCleanPaths(absIncludes)
	resolved := make([]string, 0, len(absFiles))
	seen := make(map[string]struct{}, len(absFiles))
	for _, abs := range absFiles {
		name := ""
		for _, include := range absIncludes {
			rel, err := filepath.Rel(include, abs)
			if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
				continue
			}
			name = filepath.ToSlash(rel)
			break
		}
		if name == "" {
			return nil, nil, fmt.Errorf("proto file %q is outside configured include paths", abs)
		}
		if _, ok := seen[name]; ok {
			return nil, nil, fmt.Errorf("duplicate proto input path %q", name)
		}
		seen[name] = struct{}{}
		resolved = append(resolved, name)
	}
	return resolved, absIncludes, nil
}

func uniqueCleanPaths(values []string) []string {
	out := make([]string, 0, len(values))
	seen := make(map[string]struct{}, len(values))
	for _, value := range values {
		value = filepath.Clean(value)
		if _, ok := seen[value]; ok {
			continue
		}
		seen[value] = struct{}{}
		out = append(out, value)
	}
	return out
}

func renderGRPCScaffold(plugin *protogen.Plugin, primaryFiles []*protogen.File, opts GRPCScaffoldOptions, files map[string][]byte, owned map[string]bool) error {
	type serviceSource struct {
		file    *protogen.File
		service *protogen.Service
	}
	services := make([]serviceSource, 0)
	seenServices := make(map[string]struct{})
	seenServiceOutputs := make(map[string]string)
	for _, primary := range primaryFiles {
		for _, service := range primary.Services {
			name := string(service.Desc.FullName())
			if _, exists := seenServices[name]; exists {
				return fmt.Errorf("duplicate RPC service %q", name)
			}
			outputName := strings.ToLower(service.GoName)
			if previous, exists := seenServiceOutputs[outputName]; exists {
				return fmt.Errorf("RPC services %q and %q have conflicting output name %q", previous, name, outputName)
			}
			seenServices[name] = struct{}{}
			seenServiceOutputs[outputName] = name
			services = append(services, serviceSource{file: primary, service: service})
		}
	}
	data := serviceScaffoldData(ServiceScaffoldOptions{Name: opts.Name, Module: opts.Module, Dir: opts.Dir, Kind: "rpc", Profile: string(ProfileGoZeroCompatible)})
	data["RPCService"] = string(services[0].service.Desc.FullName())
	methodRules := make([]generatedRPCMethodRule, 0)
	for _, item := range services {
		for _, method := range item.service.Methods {
			methodRules = append(methodRules, generatedRPCMethodRule{
				Service: string(item.service.Desc.FullName()),
				Method:  string(method.Desc.Name()),
			})
		}
	}
	data["RPCMethodRulesJSON"] = generatedRPCMethodTimeoutRulesJSON(methodRules)
	data["GovernanceRulesJSON"] = data["RPCMethodRulesJSON"]
	defaultRules := plugin.NewGeneratedFile("internal/config/rpc_methods.gen.go", protogen.GoImportPath(opts.Module+"/internal/config"))
	defaultRules.P("// Code generated by gofly. DO NOT EDIT.")
	writeGRPCScaffoldSources(defaultRules, primaryFiles)
	defaultRules.P("package config")
	defaultRules.P("func DefaultRPCMethodRules() []", protogen.GoIdent{GoImportPath: "github.com/imajinyun/gofly/core/governance", GoName: "Rule"}, " { return []", protogen.GoIdent{GoImportPath: "github.com/imajinyun/gofly/core/governance", GoName: "Rule"}, "{")
	for _, rule := range methodRules {
		defaultRules.P("{Name:", fmt.Sprintf("%q", generatedRPCMethodTimeoutRuleName(rule)), ", Priority:-1000, Transport:", protogen.GoIdent{GoImportPath: "github.com/imajinyun/gofly/core/governance", GoName: "TransportRPC"}, ", Service:", fmt.Sprintf("%q", rule.Service), ", Method:", fmt.Sprintf("%q", rule.Method), ", Policy:", protogen.GoIdent{GoImportPath: "github.com/imajinyun/gofly/core/governance", GoName: "Policy"}, "{Timeout:2*", protogen.GoIdent{GoImportPath: "time", GoName: "Second"}, "}},")
	}
	defaultRules.P("} }")
	defaultRules.P("func DefaultRPCMethodGovernance() ", protogen.GoIdent{GoImportPath: "github.com/imajinyun/gofly/core/governance", GoName: "Plugin"}, " { return ", protogen.GoIdent{GoImportPath: "github.com/imajinyun/gofly/core/governance", GoName: "NewPlugin"}, "(\"descriptor-rpc-method-defaults\", DefaultRPCMethodRules()...) }")
	defaultRulesContent, err := defaultRules.Content()
	if err != nil {
		return err
	}
	files["internal/config/rpc_methods.gen.go"] = defaultRulesContent
	main := strings.ReplaceAll(goZeroRPCMainTemplate, "\t\"{{.Module}}/internal/pb\"\n", "")
	if existingConfig, readErr := ReadFileUnderRoot(opts.Dir, "internal/config/config.go", "grpc shared config"); readErr == nil && bytes.Contains(existingConfig, []byte("type OpenAPIConfig struct")) {
		main = strings.ReplaceAll(main, "config.WithLoadValidator(appconfig.Validate)", "config.WithLoadValidator(func(c appconfig.Config) error { return errors.Join(appconfig.Validate(c), appconfig.ValidateRPC(c)) })")
		main = strings.Replace(main, "\t\"context\"\n", "\t\"context\"\n\t\"errors\"\n", 1)
	}
	main = strings.ReplaceAll(main, "pb.RegisterGreeterServer(grpcServer.GRPCServer(), apprpc.NewGreeterServer(stx))", "apprpc.RegisterServices(grpcServer.GRPCServer(), stx)")
	mainPath := existingCommandMainFile(opts.Dir, "-grpc")
	if mainPath == "" {
		mainPath = filepath.Join("cmd", serviceCommandName(moduleCommandBase(opts.Module, opts.Name), "rpc"), "main.go")
	}
	for path, template := range map[string]string{
		"go.mod":                                      goModTemplate,
		"Makefile":                                    makefileTemplate,
		mainPath:                                      main,
		filepath.Join("etc", opts.Name+".json"):       goZeroRPCConfigTemplate,
		filepath.Join("etc", "governance.json"):       governanceTemplate,
		"bin/production-check.sh":                     goZeroRPCProductionCheckScriptTemplate,
		"internal/config/config.go":                   goZeroRPCConfigGoTemplate,
		"internal/config/production_check.go":         goZeroRPCProductionCheckGoTemplate,
		"internal/config/governance_recovery_test.go": goZeroRPCGovernanceRecoveryTestTemplate,
		"internal/discovery/registry.go":              goZeroRPCDiscoveryTemplate,
		"internal/svc/service_context.go":             goZeroRPCSvcTemplate,
	} {
		files[path] = []byte(render(template, data))
		owned[path] = true
	}
	ident := func(path, name string) protogen.GoIdent {
		return protogen.GoIdent{GoImportPath: protogen.GoImportPath(path), GoName: name}
	}
	stx := ident(opts.Module+"/internal/svc", "ServiceContext")
	registerPath := "internal/api/grpc/v1/register.gen.go"
	combinedServer := plugin.NewGeneratedFile(registerPath, protogen.GoImportPath(opts.Module+"/internal/api/grpc/v1"))
	combinedServer.P("// Code generated by gofly. DO NOT EDIT.")
	writeGRPCScaffoldSources(combinedServer, primaryFiles)
	combinedServer.P("package rpcv1")
	combinedServer.P("func RegisterServices(registrar ", ident("google.golang.org/grpc", "ServiceRegistrar"), ", stx *", stx, ") {")
	domains := make(map[*protogen.Service]string, len(services))
	for _, item := range services {
		domain, err := grpcApplicationDomain(opts.Dir, item.service)
		if err != nil {
			return err
		}
		domains[item.service] = domain
		combinedServer.P(ident(opts.Module+"/internal/api/grpc/v1/"+domain, "Register"+item.service.GoName), "(registrar, stx)")
	}
	combinedServer.P("}")
	combinedServer.P("func DiscoveryAliases() []string { return []string{")
	for _, item := range services {
		combinedServer.P(fmt.Sprintf("%q,", item.service.Desc.FullName()))
	}
	combinedServer.P("} }")
	for _, item := range services {
		file, service := item.file, item.service
		domain := domains[service]
		serviceFile := strings.ToLower(service.GoName)
		serverPath := "internal/api/grpc/v1/" + domain + "/" + serviceFile + "_grpc.gen.go"
		server := plugin.NewGeneratedFile(serverPath, protogen.GoImportPath(opts.Module+"/internal/api/grpc/v1/"+domain))
		server.P("// Code generated by gofly. DO NOT EDIT.")
		server.P("// source: ", file.Desc.Path())
		server.P("package ", domain, "rpc")
		server.P("func Register", service.GoName, "(registrar ", ident("google.golang.org/grpc", "ServiceRegistrar"), ", stx *", stx, ") {")
		server.P(ident(string(file.GoImportPath), "Register"+service.GoName+"Server"), "(registrar, &", service.GoName, "Server{stx: stx})")
		server.P("}")
		server.P("type ", service.GoName, "Server struct {", ident(string(file.GoImportPath), "Unimplemented"+service.GoName+"Server"), "; stx *", stx, "}")
		server.P("func transcode", service.GoName, "[T any](value any, aliases map[string]string) (*T, error) { data, err := ", ident("encoding/json", "Marshal"), "(value); if err != nil { return nil, err }; if len(aliases) > 0 { var fields map[string]", ident("encoding/json", "RawMessage"), "; if err := ", ident("encoding/json", "Unmarshal"), "(data, &fields); err != nil { return nil, err }; for source, target := range aliases { if field, ok := fields[source]; ok { fields[target] = field; delete(fields, source) } }; data, err = ", ident("encoding/json", "Marshal"), "(fields); if err != nil { return nil, err } }; var target T; if err := ", ident("encoding/json", "Unmarshal"), "(data, &target); err != nil { return nil, err }; return &target, nil }")
		for _, method := range service.Methods {
			logicPath := opts.Module + "/internal/app/" + domain
			path := "internal/app/" + domain + "/" + strings.ToLower(method.GoName) + ".go"
			if _, exists := files[path]; exists {
				return fmt.Errorf("duplicate RPC logic output %q", path)
			}
			var request, serverRequest, result, serverResult string
			args, ctx := "req", "ctx"
			streaming := method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer()
			contract := grpcApplicationContract{}
			existing := false
			if streaming {
				_, statErr := os.Lstat(filepath.Join(opts.Dir, path))
				existing = statErr == nil
				if statErr != nil && !errors.Is(statErr, os.ErrNotExist) {
					return statErr
				}
			} else {
				contract, existing, err = readGRPCApplicationContract(opts.Dir, path, method.GoName)
				if err != nil {
					return err
				}
			}
			logic := plugin.NewGeneratedFile(path, protogen.GoImportPath(logicPath))
			if !existing {
				logic.P("package ", domain, "app")
				logic.P(grpcGeneratedApplicationMarker)
				logic.P("type ", method.GoName, "Logic struct {ctx ", ident("context", "Context"), "; stx *", stx, "}")
				logic.P("func New", method.GoName, "Logic(ctx ", ident("context", "Context"), ", stx *", stx, ") *", method.GoName, "Logic {return &", method.GoName, "Logic{ctx:ctx,stx:stx}}")
			}
			stub := "return nil, " + logic.QualifiedGoIdent(ident("google.golang.org/grpc/status", "Error")) + "(" + logic.QualifiedGoIdent(ident("google.golang.org/grpc/codes", "Unimplemented")) + ", \"not implemented\")"
			if streaming {
				streamType := ident(string(file.GoImportPath), service.GoName+"_"+method.GoName+"Server")
				request = "stream " + logic.QualifiedGoIdent(streamType)
				serverRequest = "stream " + server.QualifiedGoIdent(streamType)
				args, ctx = "stream", "stream.Context()"
				if !method.Desc.IsStreamingClient() {
					request = "req *" + logic.QualifiedGoIdent(method.Input.GoIdent) + ", " + request
					serverRequest = "req *" + server.QualifiedGoIdent(method.Input.GoIdent) + ", " + serverRequest
					args = "req, stream"
				}
				result, serverResult = "error", "error"
				stub = strings.Replace(stub, "return nil, ", "return ", 1)
			} else {
				request = "req *" + logic.QualifiedGoIdent(method.Input.GoIdent)
				serverRequest = "ctx " + server.QualifiedGoIdent(ident("context", "Context")) + ", req *" + server.QualifiedGoIdent(method.Input.GoIdent)
				result = "(*" + logic.QualifiedGoIdent(method.Output.GoIdent) + ", error)"
				serverResult = "(*" + server.QualifiedGoIdent(method.Output.GoIdent) + ", error)"
			}
			if !existing {
				logic.P("func (l *", method.GoName, "Logic) ", method.GoName, "(", request, ") ", result, " {", stub, "}")
				content, err := logic.Content()
				if err != nil {
					return err
				}
				files[path], owned[path] = content, true
			}
			if existing && !streaming {
				requestAliases, err := grpcApplicationAliases(opts.Dir, opts.Module, contract.RequestImport, contract.RequestType, method.Input, true)
				if err != nil {
					return err
				}
				responseAliases, err := grpcApplicationAliases(opts.Dir, opts.Module, contract.ResponseImport, contract.ResponseType, method.Output, false)
				if err != nil {
					return err
				}
				writeGRPCUnaryApplicationAdapter(server, ident, logicPath, service, method, contract, requestAliases, responseAliases)
			} else {
				server.P("func (s *", service.GoName, "Server) ", method.GoName, "(", serverRequest, ") ", serverResult, " {return ", ident(logicPath, "New"+method.GoName+"Logic"), "(", ctx, ", s.stx).", method.GoName, "(", args, ")}")
			}
		}
		content, err := server.Content()
		if err != nil {
			return err
		}
		files[serverPath] = content
	}
	serverContent, err := combinedServer.Content()
	if err != nil {
		return err
	}
	files[registerPath] = serverContent
	if opts.NoClient {
		return nil
	}
	for _, item := range services {
		file, service := item.file, item.service
		domain := domains[service]
		serviceFile := strings.ToLower(service.GoName)
		clientPath := "internal/api/grpc/v1/" + domain + "/" + serviceFile + "_client.gen.go"
		client := plugin.NewGeneratedFile(clientPath, protogen.GoImportPath(opts.Module+"/internal/api/grpc/v1/"+domain))
		client.P("// Code generated by gofly. DO NOT EDIT.")
		client.P("// source: ", file.Desc.Path())
		client.P("package ", domain, "rpc")
		client.P("func New", service.GoName, "(ctx ", ident("context", "Context"), ", target string, rules *", ident("github.com/imajinyun/gofly/core/governance", "RuleSet"), ", opts ...", ident("github.com/imajinyun/gofly/rpc/grpc", "ClientOption"), ") (", ident(string(file.GoImportPath), service.GoName+"Client"), ", *", ident("github.com/imajinyun/gofly/rpc/grpc", "ClientConn"), ", error) {")
		client.P("conn, err := ", ident("github.com/imajinyun/gofly/rpc/grpc", "NewDefaultClient"), "(ctx, target, ", fmt.Sprintf("%q", service.Desc.FullName()), ", rules, nil, opts...)")
		client.P("if err != nil {return nil,nil,err}; return ", ident(string(file.GoImportPath), "New"+service.GoName+"Client"), "(conn.Conn()),conn,nil }")
		client.P("func NewDiscovered", service.GoName, "(ctx ", ident("context", "Context"), ", resolver ", ident("github.com/imajinyun/gofly/core/discovery", "Resolver"), ", rules *", ident("github.com/imajinyun/gofly/core/governance", "RuleSet"), ", opts ...", ident("github.com/imajinyun/gofly/rpc/grpc", "ClientOption"), ") (", ident(string(file.GoImportPath), service.GoName+"Client"), ", *", ident("github.com/imajinyun/gofly/rpc/grpc", "ClientConn"), ", error) {")
		client.P("opts = append([]", ident("github.com/imajinyun/gofly/rpc/grpc", "ClientOption"), "{", ident("github.com/imajinyun/gofly/rpc/grpc", "WithDiscoveryResolverOptions"), "(resolver, ", fmt.Sprintf("%q", service.Desc.FullName()), ", []", ident("github.com/imajinyun/gofly/rpc/grpc", "ResolverOption"), "{", ident("github.com/imajinyun/gofly/rpc/grpc", "WithP2CEWMAResolver"), "()})}, opts...)")
		client.P("return New", service.GoName, "(ctx, ", ident("github.com/imajinyun/gofly/rpc/grpc", "Target"), "(", fmt.Sprintf("%q", service.Desc.FullName()), "), rules, opts...) }")
		client.P("func NewConfigured", service.GoName, "(ctx ", ident("context", "Context"), ", resolver ", ident("github.com/imajinyun/gofly/core/discovery", "Resolver"), ", cfg ", ident(opts.Module+"/internal/config", "RPCClientConfig"), ", rules *", ident("github.com/imajinyun/gofly/core/governance", "RuleSet"), ", opts ...", ident("github.com/imajinyun/gofly/rpc/grpc", "ClientOption"), ") (", ident(string(file.GoImportPath), service.GoName+"Client"), ", *", ident("github.com/imajinyun/gofly/rpc/grpc", "ClientConn"), ", error) {")
		client.P(fmt.Sprintf("target, configured, err := cfg.TargetAndOptions(resolver, %q); if err != nil {return nil,nil,err}", service.Desc.FullName()))
		client.P("opts = append(configured, opts...)")
		client.P("return New", service.GoName, "(ctx, target, rules, opts...) }")
		content, err := client.Content()
		if err != nil {
			return err
		}
		if _, exists := files[clientPath]; exists {
			return fmt.Errorf("duplicate RPC client output %q", clientPath)
		}
		files[clientPath] = content
	}
	return nil
}

func writeGRPCScaffoldSources(file *protogen.GeneratedFile, primaryFiles []*protogen.File) {
	for _, primary := range primaryFiles {
		file.P("// source: ", primary.Desc.Path())
	}
}

func grpcApplicationDomain(root string, service *protogen.Service) (string, error) {
	candidates := []string{lowerName(strings.TrimSuffix(service.GoName, "Service"))}
	packageName := strings.TrimSpace(string(service.Desc.ParentFile().Package()))
	if packageName != "" {
		candidates = append(candidates, lowerName(strings.Split(packageName, ".")[0]))
	}
	appRoot, err := SafeTarget(root, filepath.Join("internal", "app"), "grpc application domain")
	if err != nil {
		return "", err
	}
	entries, err := os.ReadDir(appRoot)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return "", fmt.Errorf("read grpc application domains: %w", err)
	}
	bestName, bestMatches, bestCount := "", 0, 0
	for _, entry := range entries {
		if !entry.IsDir() || entry.Type()&os.ModeSymlink != 0 {
			continue
		}
		matches := 0
		for _, method := range service.Methods {
			path := filepath.Join(appRoot, entry.Name(), strings.ToLower(method.GoName)+".go")
			if info, statErr := os.Lstat(path); statErr == nil && info.Mode().IsRegular() {
				matches++
			}
		}
		for _, candidate := range candidates {
			if entry.Name() == candidate && matches > 0 {
				return entry.Name(), nil
			}
		}
		if matches > bestMatches {
			bestName, bestMatches, bestCount = entry.Name(), matches, 1
		} else if matches == bestMatches && matches > 0 {
			bestCount++
		}
	}
	if bestMatches > 0 {
		if bestCount > 1 {
			return "", fmt.Errorf("cannot infer one application domain for RPC service %q: %d directories match its methods", service.Desc.FullName(), bestCount)
		}
		return bestName, nil
	}
	for _, candidate := range candidates {
		if token.IsIdentifier(candidate) {
			return candidate, nil
		}
	}
	return "", fmt.Errorf("cannot derive application domain for RPC service %q", service.Desc.FullName())
}

func readGRPCApplicationContract(root, path, methodName string) (grpcApplicationContract, bool, error) {
	data, err := ReadFileUnderRoot(root, path, "grpc application contract")
	if errors.Is(err, os.ErrNotExist) {
		return grpcApplicationContract{}, false, nil
	}
	if err != nil {
		return grpcApplicationContract{}, false, err
	}
	if bytes.Contains(data, []byte(grpcGeneratedApplicationMarker)) {
		return grpcApplicationContract{}, false, nil
	}
	parsed, err := parser.ParseFile(token.NewFileSet(), path, data, 0)
	if err != nil {
		return grpcApplicationContract{}, false, fmt.Errorf("parse grpc application contract %s: %w", path, err)
	}
	imports := make(map[string]string, len(parsed.Imports))
	for _, spec := range parsed.Imports {
		importPath := strings.Trim(spec.Path.Value, "\"")
		name := filepath.Base(importPath)
		if spec.Name != nil {
			name = spec.Name.Name
		}
		imports[name] = importPath
	}
	for _, decl := range parsed.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || fn.Name.Name != methodName || fn.Recv == nil || fn.Type.Results == nil || len(fn.Type.Results.List) == 0 {
			continue
		}
		contract := grpcApplicationContract{}
		if fn.Type.Params != nil && len(fn.Type.Params.List) > 0 {
			importPath, name, ok := grpcContractType(fn.Type.Params.List[0].Type, imports)
			if !ok {
				return grpcApplicationContract{}, false, fmt.Errorf("application method %s in %s must use a named request type", methodName, path)
			}
			contract.RequestImport, contract.RequestType, contract.HasRequest = importPath, name, true
		}
		importPath, name, ok := grpcContractType(fn.Type.Results.List[0].Type, imports)
		if !ok {
			return grpcApplicationContract{}, false, fmt.Errorf("application method %s in %s must return a named response type", methodName, path)
		}
		contract.ResponseImport, contract.ResponseType = importPath, name
		return contract, true, nil
	}
	return grpcApplicationContract{}, false, fmt.Errorf("application file %s does not define method %s", path, methodName)
}

func grpcContractType(expr ast.Expr, imports map[string]string) (string, string, bool) {
	if pointer, ok := expr.(*ast.StarExpr); ok {
		expr = pointer.X
	}
	selector, ok := expr.(*ast.SelectorExpr)
	if !ok {
		return "", "", false
	}
	packageName, ok := selector.X.(*ast.Ident)
	if !ok {
		return "", "", false
	}
	importPath, ok := imports[packageName.Name]
	return importPath, selector.Sel.Name, ok
}

func writeGRPCUnaryApplicationAdapter(server *protogen.GeneratedFile, ident func(string, string) protogen.GoIdent, logicPath string, service *protogen.Service, method *protogen.Method, contract grpcApplicationContract, requestAliases, responseAliases map[string]string) {
	server.P("func (s *", service.GoName, "Server) ", method.GoName, "(ctx ", ident("context", "Context"), ", req *", method.Input.GoIdent, ") (*", method.Output.GoIdent, ", error) {")
	if contract.HasRequest {
		server.P("appReq, err := transcode", service.GoName, "[", ident(contract.RequestImport, contract.RequestType), "](req, ", grpcAliasLiteral(requestAliases), ")")
		server.P("if err != nil { return nil, ", ident("google.golang.org/grpc/status", "Errorf"), "(", ident("google.golang.org/grpc/codes", "InvalidArgument"), ", \"decode ", method.GoName, " request: %v\", err) }")
		server.P("appResp, err := ", ident(logicPath, "New"+method.GoName+"Logic"), "(ctx, s.stx).", method.GoName, "(appReq)")
	} else {
		server.P("appResp, err := ", ident(logicPath, "New"+method.GoName+"Logic"), "(ctx, s.stx).", method.GoName, "()")
	}
	server.P("if err != nil { return nil, ", ident("github.com/imajinyun/gofly/core/errors", "GRPCError"), "(err) }")
	server.P("resp, err := transcode", service.GoName, "[", method.Output.GoIdent, "](appResp, ", grpcAliasLiteral(responseAliases), ")")
	server.P("if err != nil { return nil, ", ident("google.golang.org/grpc/status", "Errorf"), "(", ident("google.golang.org/grpc/codes", "Internal"), ", \"encode ", method.GoName, " response: %v\", err) }")
	server.P("return resp, nil")
	server.P("}")
}

func grpcApplicationAliases(root, module, importPath, typeName string, message *protogen.Message, request bool) (map[string]string, error) {
	if strings.TrimSpace(importPath) == "" || strings.TrimSpace(typeName) == "" {
		return nil, nil
	}
	applicationFields, err := grpcApplicationJSONFields(root, module, importPath, typeName)
	if err != nil {
		return nil, err
	}
	protoFields := make([]string, 0, message.Desc.Fields().Len())
	for index := 0; index < message.Desc.Fields().Len(); index++ {
		protoFields = append(protoFields, message.Desc.Fields().Get(index).JSONName())
	}
	if request {
		return grpcInferAliases(protoFields, applicationFields), nil
	}
	return grpcInferAliases(applicationFields, protoFields), nil
}

func grpcApplicationJSONFields(root, module, importPath, typeName string) ([]string, error) {
	prefix := strings.TrimRight(module, "/") + "/"
	if !strings.HasPrefix(importPath, prefix) {
		return nil, nil
	}
	modelDir := filepath.FromSlash(strings.TrimPrefix(importPath, prefix))
	dir, err := SafeTarget(root, modelDir, "grpc application model")
	if err != nil {
		return nil, err
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("read grpc application model package %s: %w", importPath, err)
	}
	for _, entry := range entries {
		if entry.IsDir() || entry.Type()&os.ModeSymlink != 0 || filepath.Ext(entry.Name()) != ".go" {
			continue
		}
		rel := filepath.Join(modelDir, entry.Name())
		data, err := ReadFileUnderRoot(root, rel, "grpc application model")
		if err != nil {
			return nil, err
		}
		file, err := parser.ParseFile(token.NewFileSet(), rel, data, 0)
		if err != nil {
			return nil, fmt.Errorf("parse grpc application model file %s: %w", rel, err)
		}
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok {
				continue
			}
			for _, spec := range gen.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok || typeSpec.Name.Name != typeName {
					continue
				}
				structure, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					return nil, fmt.Errorf("grpc application model %s.%s must be a struct", importPath, typeName)
				}
				fields := make([]string, 0, len(structure.Fields.List))
				for _, field := range structure.Fields.List {
					if len(field.Names) == 0 || !field.Names[0].IsExported() {
						continue
					}
					name := lowerName(field.Names[0].Name)
					if field.Tag != nil {
						tag := reflect.StructTag(strings.Trim(field.Tag.Value, string(rune(96))))
						if jsonName := strings.Split(tag.Get("json"), ",")[0]; jsonName != "" && jsonName != "-" {
							name = jsonName
						}
					}
					fields = append(fields, name)
				}
				return fields, nil
			}
		}
	}
	return nil, fmt.Errorf("grpc application model %s.%s was not found", importPath, typeName)
}

func grpcInferAliases(source, target []string) map[string]string {
	targetSet := make(map[string]struct{}, len(target))
	for _, name := range target {
		targetSet[strings.ToLower(name)] = struct{}{}
	}
	sourceSet := make(map[string]struct{}, len(source))
	for _, name := range source {
		sourceSet[strings.ToLower(name)] = struct{}{}
	}
	var sourceOnly, targetOnly []string
	for _, name := range source {
		if _, ok := targetSet[strings.ToLower(name)]; !ok {
			sourceOnly = append(sourceOnly, name)
		}
	}
	for _, name := range target {
		if _, ok := sourceSet[strings.ToLower(name)]; !ok {
			targetOnly = append(targetOnly, name)
		}
	}
	if len(sourceOnly) == 1 && len(targetOnly) == 1 {
		return map[string]string{sourceOnly[0]: targetOnly[0]}
	}
	return nil
}

func grpcAliasLiteral(aliases map[string]string) string {
	if len(aliases) == 0 {
		return "nil"
	}
	keys := make([]string, 0, len(aliases))
	for key := range aliases {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	var b strings.Builder
	b.WriteString("map[string]string{")
	for _, key := range keys {
		fmt.Fprintf(&b, "%q:%q,", key, aliases[key])
	}
	b.WriteString("}")
	return b.String()
}
