package generator

import (
	"fmt"
	"go/format"
	"path/filepath"
	"strconv"
	"strings"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

type ProtocPluginOptions struct {
	Module           string
	NameFromFilename bool
	NoClient         bool
	Multiple         bool
}

func GenerateProtocPluginResponse(req *pluginpb.CodeGeneratorRequest, opts ProtocPluginOptions) (*pluginpb.CodeGeneratorResponse, error) {
	if req == nil {
		return nil, fmt.Errorf("protoc request is nil")
	}
	opts = mergeProtocPluginOptions(opts, req.GetParameter())
	files := map[string]*descriptorpb.FileDescriptorProto{}
	for _, file := range req.GetProtoFile() {
		files[file.GetName()] = file
	}
	targets := req.GetFileToGenerate()
	if len(targets) == 0 {
		for _, file := range req.GetProtoFile() {
			targets = append(targets, file.GetName())
		}
	}
	resp := &pluginpb.CodeGeneratorResponse{}
	for _, name := range targets {
		file := files[name]
		if file == nil {
			return nil, fmt.Errorf("file to generate %q not found in request", name)
		}
		if len(file.GetService()) == 0 {
			continue
		}
		generatedFiles, err := renderProtocPluginFiles(file, opts)
		if err != nil {
			return nil, err
		}
		for _, generated := range generatedFiles {
			resp.File = append(resp.File, &pluginpb.CodeGeneratorResponse_File{
				Name:    proto.String(generated.Name),
				Content: proto.String(generated.Content),
			})
		}
	}
	return resp, nil
}

func mergeProtocPluginOptions(opts ProtocPluginOptions, parameter string) ProtocPluginOptions {
	for _, part := range strings.Split(parameter, ",") {
		key, value, ok := strings.Cut(strings.TrimSpace(part), "=")
		if !ok {
			continue
		}
		switch strings.ToLower(strings.TrimSpace(key)) {
		case "module":
			opts.Module = strings.TrimSpace(value)
		case "name_from_filename", "name-from-filename":
			opts.NameFromFilename = parseProtocBool(value)
		case "no_client", "no-client":
			opts.NoClient = parseProtocBool(value)
		case "multiple":
			opts.Multiple = parseProtocBool(value)
		}
	}
	return opts
}

func parseProtocBool(value string) bool {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "1", "t", "true", "y", "yes":
		return true
	default:
		return false
	}
}

func MarshalProtocPluginResponse(reqData []byte, opts ProtocPluginOptions) ([]byte, error) {
	req := &pluginpb.CodeGeneratorRequest{}
	if err := proto.Unmarshal(reqData, req); err != nil {
		return nil, fmt.Errorf("decode protoc request: %w", err)
	}
	resp, err := GenerateProtocPluginResponse(req, opts)
	if err != nil {
		return nil, err
	}
	out, err := proto.Marshal(resp)
	if err != nil {
		return nil, fmt.Errorf("encode protoc response: %w", err)
	}
	return out, nil
}

type protocPluginGeneratedFile struct {
	Name    string
	Content string
}

type protocPluginMethod struct {
	Name            string
	Request         string
	Response        string
	ClientStreaming bool
	ServerStreaming bool
}

func renderProtocPluginFiles(file *descriptorpb.FileDescriptorProto, opts ProtocPluginOptions) ([]protocPluginGeneratedFile, error) {
	if !opts.Multiple {
		name, content, err := renderProtocPluginFile(file, nil, opts)
		if err != nil {
			return nil, err
		}
		return []protocPluginGeneratedFile{{Name: name, Content: content}}, nil
	}
	out := make([]protocPluginGeneratedFile, 0, len(file.GetService()))
	for _, svc := range file.GetService() {
		name, content, err := renderProtocPluginFile(file, []*descriptorpb.ServiceDescriptorProto{svc}, opts)
		if err != nil {
			return nil, err
		}
		base := strings.TrimSuffix(name, filepath.Ext(name))
		out = append(out, protocPluginGeneratedFile{
			Name:    filepath.Join(lowerSnake(svc.GetName()), base+".go"),
			Content: content,
		})
	}
	return out, nil
}

func renderProtocPluginFile(file *descriptorpb.FileDescriptorProto, services []*descriptorpb.ServiceDescriptorProto, opts ProtocPluginOptions) (string, string, error) {
	pkg := goPackageName(file)
	base := strings.TrimSuffix(file.GetName(), filepath.Ext(file.GetName()))
	outName := base + ".gofly.go"
	if services == nil {
		services = file.GetService()
	}
	servicePrefix := ""
	if opts.NameFromFilename {
		servicePrefix = exportName(filepath.Base(base))
	}
	var b strings.Builder
	b.WriteString("// Code generated by gofly protoc plugin. DO NOT EDIT.\n\n")
	b.WriteString("package " + pkg + "\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"github.com/gofly/gofly/rpc\"\n")
	b.WriteString(")\n\n")
	if opts.Module != "" {
		b.WriteString("// Module: " + sanitizeGeneratedCommentLine(opts.Module) + "\n\n")
	}
	for _, svc := range services {
		serviceName := exportName(servicePrefix + svc.GetName())
		serviceFullName := protocServiceFullName(file, svc)
		methods, err := collectProtocPluginMethods(file, svc, serviceFullName)
		if err != nil {
			return "", "", err
		}
		unaryMethods := protocUnaryMethods(methods)
		streamMethods := protocStreamMethods(methods)
		b.WriteString("func " + serviceName + "GoflyDescriptor() rpc.ServiceDesc {\n")
		b.WriteString("\treturn rpc.ServiceDesc{Name: " + quoteGoString(serviceFullName))
		if len(unaryMethods) > 0 {
			b.WriteString(", Methods: []rpc.MethodDesc{\n")
		} else if len(streamMethods) > 0 {
			b.WriteString(",\n")
		}
		for _, method := range unaryMethods {
			b.WriteString("\t\t{Name: " + quoteGoString(method.Name) + ", NewRequest: func() any { return new(" + method.Request + ") }, Request: " + quoteGoString(method.Request) + ", Response: " + quoteGoString(method.Response) + "},\n")
		}
		if len(unaryMethods) > 0 {
			b.WriteString("\t}")
		}
		if len(streamMethods) > 0 {
			if len(unaryMethods) > 0 {
				b.WriteString(", Streams: []rpc.StreamDesc{\n")
			} else {
				b.WriteString("\tStreams: []rpc.StreamDesc{\n")
			}
			for _, method := range streamMethods {
				message := protocStreamMessageName(method)
				b.WriteString("\t\t{Name: " + quoteGoString(method.Name) + ", NewMessage: func() any { return new(" + message + ") }, Message: " + quoteGoString(message) + ", Mode: " + protocStreamModeLiteral(method) + ", Metadata: map[string]string{\"request\": " + quoteGoString(method.Request) + ", \"response\": " + quoteGoString(method.Response) + ", \"clientStream\": " + quoteGoString(strconv.FormatBool(method.ClientStreaming)) + ", \"serverStream\": " + quoteGoString(strconv.FormatBool(method.ServerStreaming)) + "}},\n")
			}
			b.WriteString("\t}")
		}
		b.WriteString("}\n")
		b.WriteString("}\n\n")
		b.WriteString("func " + serviceName + "GoflyRuntimeDescriptor() rpc.Descriptor {\n")
		b.WriteString("\treturn " + serviceName + "GoflyDescriptor().Descriptor()\n")
		b.WriteString("}\n\n")
		b.WriteString("// " + serviceName + "GoflyService describes the gofly RPC surface generated from " + sanitizeGeneratedCommentLine(file.GetName()) + ".\n")
		b.WriteString("type " + serviceName + "GoflyService interface {\n")
		for _, method := range methods {
			if method.ClientStreaming || method.ServerStreaming {
				b.WriteString("\t" + method.Name + "(ctx context.Context, stream *rpc.Stream) error\n")
				continue
			}
			b.WriteString("\t" + method.Name + "(ctx context.Context, req *" + method.Request + ") (*" + method.Response + ", error)\n")
		}
		b.WriteString("}\n\n")
		b.WriteString("func " + serviceName + "GoflyServiceDesc(impl " + serviceName + "GoflyService) rpc.ServiceDesc {\n")
		b.WriteString("\tdesc := " + serviceName + "GoflyDescriptor()\n")
		for i, method := range unaryMethods {
			writeDefensiveHandlerBinding(&b, i, method.Name, method.Request)
		}
		for i, method := range streamMethods {
			b.WriteString("\tdesc.Streams[" + strconv.Itoa(i) + "].Handler = func(ctx context.Context, stream *rpc.Stream) error {\n")
			b.WriteString("\t\treturn impl." + method.Name + "(ctx, stream)\n")
			b.WriteString("\t}\n")
		}
		b.WriteString("\treturn desc\n")
		b.WriteString("}\n\n")
		b.WriteString("func Bind" + serviceName + "GoflyGenericHandlers(handlers map[string]rpc.GenericHandler) (rpc.ServiceDesc, error) {\n")
		b.WriteString("\treturn rpc.BindGenericHandlers(" + serviceName + "GoflyDescriptor(), handlers)\n")
		b.WriteString("}\n\n")
		b.WriteString("func Register" + serviceName + "GoflyServer(s *rpc.HTTPServer, impl " + serviceName + "GoflyService) error {\n")
		b.WriteString("\treturn s.RegisterService(" + serviceName + "GoflyServiceDesc(impl), impl)\n")
		b.WriteString("}\n\n")
		b.WriteString("func New" + serviceName + "GoflyHTTPServer(impl " + serviceName + "GoflyService, opts ...rpc.ServerOption) (*rpc.HTTPServer, error) {\n")
		b.WriteString("\tserver := rpc.NewServer(opts...)\n")
		b.WriteString("\tif err := Register" + serviceName + "GoflyServer(server, impl); err != nil {\n")
		b.WriteString("\t\treturn nil, err\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn server, nil\n")
		b.WriteString("}\n\n")
		if !opts.NoClient {
			b.WriteString("type " + serviceName + "GoflyClient interface {\n")
			for _, method := range methods {
				if method.ClientStreaming || method.ServerStreaming {
					b.WriteString("\t" + method.Name + "(ctx context.Context) (*rpc.Stream, error)\n")
					continue
				}
				b.WriteString("\t" + method.Name + "(ctx context.Context, req *" + method.Request + ") (*" + method.Response + ", error)\n")
			}
			b.WriteString("}\n\n")
			b.WriteString("type " + serviceName + "GoflyRPCClient struct {\n")
			b.WriteString("\tcc   rpc.Client\n")
			b.WriteString("\tdesc rpc.ServiceDesc\n")
			b.WriteString("}\n\n")
			b.WriteString("func New" + serviceName + "GoflyClient(cc rpc.Client) *" + serviceName + "GoflyRPCClient {\n")
			b.WriteString("\treturn &" + serviceName + "GoflyRPCClient{cc: cc, desc: " + serviceName + "GoflyDescriptor()}\n")
			b.WriteString("}\n\n")
			b.WriteString("func New" + serviceName + "GoflyHTTPClient(target string, opts ...rpc.ClientOption) (*" + serviceName + "GoflyRPCClient, error) {\n")
			b.WriteString("\tclient, err := rpc.NewClient(target, opts...)\n")
			b.WriteString("\tif err != nil {\n")
			b.WriteString("\t\treturn nil, err\n")
			b.WriteString("\t}\n")
			b.WriteString("\treturn New" + serviceName + "GoflyClient(client), nil\n")
			b.WriteString("}\n\n")
			b.WriteString("func (c *" + serviceName + "GoflyRPCClient) Descriptor() rpc.ServiceDesc {\n")
			b.WriteString("\treturn rpc.CloneServiceDesc(c.desc)\n")
			b.WriteString("}\n\n")
			b.WriteString("func (c *" + serviceName + "GoflyRPCClient) RuntimeDescriptor() rpc.Descriptor {\n")
			b.WriteString("\treturn c.desc.Descriptor()\n")
			b.WriteString("}\n\n")
			for _, method := range methods {
				if method.ClientStreaming || method.ServerStreaming {
					b.WriteString("func (c *" + serviceName + "GoflyRPCClient) " + method.Name + "(ctx context.Context) (*rpc.Stream, error) {\n")
					b.WriteString("\tmethod, err := c.desc.StreamPath(" + quoteGoString(method.Name) + ")\n")
					b.WriteString("\tif err != nil {\n")
					b.WriteString("\t\treturn nil, err\n")
					b.WriteString("\t}\n")
					b.WriteString("\tstreamer, ok := c.cc.(interface { Stream(context.Context, string) (*rpc.Stream, error) })\n")
					b.WriteString("\tif !ok {\n")
					b.WriteString("\t\treturn nil, rpc.NewError(rpc.CodeUnimplemented, \"rpc client does not support streaming\")\n")
					b.WriteString("\t}\n")
					b.WriteString("\treturn streamer.Stream(ctx, method)\n")
					b.WriteString("}\n\n")
					continue
				}
				b.WriteString("func (c *" + serviceName + "GoflyRPCClient) " + method.Name + "(ctx context.Context, req *" + method.Request + ") (*" + method.Response + ", error) {\n")
				b.WriteString("\tvar resp " + method.Response + "\n")
				b.WriteString("\tmethod, err := c.desc.MethodPath(" + quoteGoString(method.Name) + ")\n")
				b.WriteString("\tif err != nil {\n")
				b.WriteString("\t\treturn nil, err\n")
				b.WriteString("\t}\n")
				b.WriteString("\tif err := c.cc.Call(ctx, method, req, &resp); err != nil {\n")
				b.WriteString("\t\treturn nil, err\n")
				b.WriteString("\t}\n")
				b.WriteString("\treturn &resp, nil\n")
				b.WriteString("}\n\n")
			}
			b.WriteString("type " + serviceName + "GoflyGenericClient struct {\n")
			b.WriteString("\tinvoker *rpc.GenericInvoker\n")
			b.WriteString("\tdesc    rpc.ServiceDesc\n")
			b.WriteString("}\n\n")
			b.WriteString("func New" + serviceName + "GoflyGenericClient(client rpc.GenericClient) (*" + serviceName + "GoflyGenericClient, error) {\n")
			b.WriteString("\tinvoker, err := rpc.NewGenericInvoker(client)\n")
			b.WriteString("\tif err != nil {\n")
			b.WriteString("\t\treturn nil, err\n")
			b.WriteString("\t}\n")
			b.WriteString("\treturn &" + serviceName + "GoflyGenericClient{invoker: invoker, desc: " + serviceName + "GoflyDescriptor()}, nil\n")
			b.WriteString("}\n\n")
			b.WriteString("func New" + serviceName + "GoflyGenericHTTPClient(target string, opts ...rpc.ClientOption) (*" + serviceName + "GoflyGenericClient, error) {\n")
			b.WriteString("\tclient, err := rpc.NewClient(target, opts...)\n")
			b.WriteString("\tif err != nil {\n")
			b.WriteString("\t\treturn nil, err\n")
			b.WriteString("\t}\n")
			b.WriteString("\treturn New" + serviceName + "GoflyGenericClient(client)\n")
			b.WriteString("}\n\n")
			b.WriteString("func (c *" + serviceName + "GoflyGenericClient) Descriptor() rpc.ServiceDesc {\n")
			b.WriteString("\treturn rpc.CloneServiceDesc(c.desc)\n")
			b.WriteString("}\n\n")
			b.WriteString("func (c *" + serviceName + "GoflyGenericClient) RuntimeDescriptor() rpc.Descriptor {\n")
			b.WriteString("\treturn c.desc.Descriptor()\n")
			b.WriteString("}\n\n")
			b.WriteString("func (c *" + serviceName + "GoflyGenericClient) Invoke(ctx context.Context, method string, req any) (rpc.GenericResponse, error) {\n")
			b.WriteString("\treturn c.invoker.InvokeMethod(ctx, c.desc, method, req)\n")
			b.WriteString("}\n\n")
		}
	}
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", "", fmt.Errorf("format protoc plugin output %s: %w", outName, err)
	}
	return outName, string(formatted), nil
}

func collectProtocPluginMethods(file *descriptorpb.FileDescriptorProto, svc *descriptorpb.ServiceDescriptorProto, serviceFullName string) ([]protocPluginMethod, error) {
	methods := make([]protocPluginMethod, 0, len(svc.GetMethod()))
	for _, method := range svc.GetMethod() {
		methodName := exportName(method.GetName())
		requestName, err := protocLocalGoType(file, method.GetInputType())
		if err != nil {
			return nil, fmt.Errorf("resolve request type for %s.%s: %w", serviceFullName, methodName, err)
		}
		responseName, err := protocLocalGoType(file, method.GetOutputType())
		if err != nil {
			return nil, fmt.Errorf("resolve response type for %s.%s: %w", serviceFullName, methodName, err)
		}
		methods = append(methods, protocPluginMethod{
			Name:            methodName,
			Request:         requestName,
			Response:        responseName,
			ClientStreaming: method.GetClientStreaming(),
			ServerStreaming: method.GetServerStreaming(),
		})
	}
	return methods, nil
}

func protocUnaryMethods(methods []protocPluginMethod) []protocPluginMethod {
	out := make([]protocPluginMethod, 0, len(methods))
	for _, method := range methods {
		if method.ClientStreaming || method.ServerStreaming {
			continue
		}
		out = append(out, method)
	}
	return out
}

func protocStreamMethods(methods []protocPluginMethod) []protocPluginMethod {
	out := make([]protocPluginMethod, 0, len(methods))
	for _, method := range methods {
		if !method.ClientStreaming && !method.ServerStreaming {
			continue
		}
		out = append(out, method)
	}
	return out
}

func protocStreamMessageName(method protocPluginMethod) string {
	if method.ClientStreaming || method.Request == method.Response {
		return method.Request
	}
	return method.Response
}

func protocStreamModeLiteral(method protocPluginMethod) string {
	switch {
	case method.ClientStreaming && method.ServerStreaming:
		return "rpc.StreamModeBidiStream"
	case method.ClientStreaming:
		return "rpc.StreamModeClientStream"
	case method.ServerStreaming:
		return "rpc.StreamModeServerStream"
	default:
		return "rpc.StreamModeUnary"
	}
}

func protocServiceFullName(file *descriptorpb.FileDescriptorProto, svc *descriptorpb.ServiceDescriptorProto) string {
	if file.GetPackage() == "" {
		return svc.GetName()
	}
	return file.GetPackage() + "." + svc.GetName()
}

func goPackageName(file *descriptorpb.FileDescriptorProto) string {
	goPkg := file.GetOptions().GetGoPackage()
	if goPkg != "" {
		if idx := strings.LastIndex(goPkg, ";"); idx >= 0 {
			return sanitizePackageName(goPkg[idx+1:])
		}
		if idx := strings.LastIndex(goPkg, "/"); idx >= 0 {
			return sanitizePackageName(goPkg[idx+1:])
		}
		return sanitizePackageName(goPkg)
	}
	if file.GetPackage() != "" {
		parts := strings.Split(file.GetPackage(), ".")
		return sanitizePackageName(parts[len(parts)-1])
	}
	return "proto"
}

func sanitizePackageName(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return "proto"
	}
	var b strings.Builder
	for i, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || r == '_' || (i > 0 && r >= '0' && r <= '9') {
			b.WriteRune(r)
			continue
		}
		b.WriteByte('_')
	}
	if b.Len() == 0 {
		return "proto"
	}
	return b.String()
}

func quoteGoString(s string) string {
	return strconv.Quote(s)
}

func sanitizeGeneratedCommentLine(s string) string {
	s = strings.ReplaceAll(s, "\r\n", "\n")
	s = strings.ReplaceAll(s, "\r", "\n")
	parts := strings.Fields(s)
	return strings.Join(parts, " ")
}

func protocLocalGoType(file *descriptorpb.FileDescriptorProto, protoType string) (string, error) {
	protoType = strings.TrimPrefix(strings.TrimSpace(protoType), ".")
	if protoType == "" {
		return "", fmt.Errorf("proto type is empty")
	}
	parts := strings.Split(protoType, ".")
	if len(parts) == 0 {
		return "", fmt.Errorf("proto type %q is invalid", protoType)
	}
	pkg := strings.TrimSpace(file.GetPackage())
	if pkg != "" {
		pkgParts := strings.Split(pkg, ".")
		if len(parts) > 1 {
			if len(parts) <= len(pkgParts) {
				return "", fmt.Errorf("proto type %q is invalid", protoType)
			}
			for i, part := range pkgParts {
				if parts[i] != part {
					return "", fmt.Errorf("external proto type %q is not supported", protoType)
				}
			}
			parts = parts[len(pkgParts):]
		}
	}
	out := make([]string, 0, len(parts))
	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part == "" {
			return "", fmt.Errorf("proto type %q is invalid", protoType)
		}
		out = append(out, exportName(part))
	}
	return strings.Join(out, "_"), nil
}
