apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../k8s/deployment.yaml
  - ../../../k8s/servicemonitor.yaml
  - ../../../k8s/hpa.yaml
  - ../../../k8s/pdb.yaml
  - ../../../k8s/networkpolicy.yaml

commonLabels:
  app.kubernetes.io/part-of: gofly
  gofly.dev/profile: production
