// Code generated by gofly. DO NOT EDIT.

package rpcv1

import (
	greeterrpc "github.com/imajinyun/gofly/examples/gosky/internal/api/grpc/v1/greeter"
	"github.com/imajinyun/gofly/examples/gosky/internal/svc"
	"github.com/imajinyun/gofly/rpc"
)

func RegisterServices(server *rpc.HTTPServer, stx *svc.ServiceContext) error {
	return server.RegisterService(greeterrpc.GreeterService(stx), nil)
}
